yolo_model:

  config_file:
    name: yolo-obj.cfg
  weight_file:
    name: yolo-obj.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - buoy_red
      - buoy_green
      - buoy_yellow
      - qual_gate
      - channel
